experiment_name: "RL_BioAug_PTB_XL_ResNet1D"
seed: 42
device: "cuda"

dataset_name: "ptb-xl"
data_dir: "./data/ptb-xl/"
split_ratio: 0.8

batch_size: 128
num_workers: 4


feat_dim: 128

# Agent Settings
agent_hidden: 128
agent_seq_len: 10
nhead: 4
num_layers: 2

# Actions (ECG 특화 Baseline Wander 포함 7개)
num_actions: 7

# ==========================================
# Optimization
# ==========================================
epochs: 100
lr_enc: 0.0003
lr_agent: 0.000003
temp: 0.1